Repository devintern-esewa/March-23-Batch, pull requests merged in 2023-04, with the labels that each got.

#5 Update README.md
  README.md
Labels: setup

#8 [#1] remove screenshot from readme
  README.md
Labels: setup

#11 [#10] Remove unintended file
  plain/src/main/java/com/esewa/internship/rupeshsunuwar
Labels: cleanup

#16 [#3] Add folder for my later projects
  plain/src/main/java/com/esewa/internship/rujalmanandhar/Readme.md
Labels: enhancement

#14 Gsherpa 3
  plain/src/main/java/com/esewa/internship/gyalbusherpa/README.md
Labels: documentation

#18 S paudel 3
  plain/src/main/java/com/esewa/internship/sumanpaudel/README.md
Labels: documentation

#15 R ranjitkar 3
  plain/src/main/java/com/esewa/internship/rujanranjitkar/README.md
Labels: documentation

#17 A shrestha 3
  plain/src/main/java/com/esewa/internship/anujmanishrestha/README.md
Labels: documentation

#26 [#24] Add Two project in rupesh folder
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/com/database/Db_Conn.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/com/model/User.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/WEB-INF/web.xml
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/adduser-error.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/adduser-success.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/adduser.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/adduserform.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/deleteuser.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/editform.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/edituser.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/index.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/userform.html
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/CRUDJSP/src/main/webapp/viewusers.jsp
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/pom.xml
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/leet/Test.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/library/dao/BookRepository.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/library/model/Book.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/library/service/BookService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/library/service/BookServiceImpl.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/mockito/ScoreCollection.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/mockito/Scoreable.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/mockito/note.txt
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/nt/dao/LoginDAO.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/nt/service/LoginMgmtService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/nt/service/LoginMgmtServiceImpl.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/unittesting/BankLoanService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/unittesting/CensusService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/main/java/com/unittesting/Printer.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/BookServiceTest.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/LoginMgmtServiceTest.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/MockVsSpyTest.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/PrinterTest.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/ScoreCollectionTest.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/TestBankLoanService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/TestCensusService.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/src/test/java/TestList.java
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/target/classes/classpath.index
  plain/src/main/java/com/esewa/internship/rupeshsunuwar/junitTestingProject/target/test-classes/classpath.index
Labels: good first issue

#40 [#38]add simple spring mvc project
  badsnashrestha/Spring/SpringMVC/META-INF/application.xml
  badsnashrestha/Spring/SpringMVC/SpringMVC.iml
  badsnashrestha/Spring/SpringMVC/pom.xml
  badsnashrestha/Spring/SpringMVC/src/main/java/controller/HelloController.java
  badsnashrestha/Spring/SpringMVC/src/main/java/controller/StudentController.java
  badsnashrestha/Spring/SpringMVC/src/main/java/exception/SpringException.java
  badsnashrestha/Spring/SpringMVC/src/main/java/model/Student.java
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/HelloWeb-servlet.xml
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/jsp/ExceptionPage.jsp
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/jsp/error.jsp
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/jsp/hello.jsp
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/jsp/result.jsp
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/jsp/student.jsp
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/pages/final.html
  badsnashrestha/Spring/SpringMVC/src/main/webapp/WEB-INF/web.xml
  badsnashrestha/Spring/SpringMVC/src/main/webapp/index.jsp
Labels: good first issue

#42 [#38] add spring mvc love calculator project with functionality
  gyalbusherpa/spring/SpringMVCprojectDemo/pom.xml
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/annotation/AgeValidator.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/annotation/Don.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/api/CommunicationDTO.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/api/EmailDTO.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/api/Phone.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/api/UserInfoDTO.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/api/UserRegisterDTO.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/config/LoveCalculatorAppConfig.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/config/LoveCalculatorInitializer.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/controller/EmailController.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/controller/LCAppController.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/controller/RegistrationController.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/formatter/PhoneNumberFormatter.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/service/LCAppServiceImpl.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/java/com/service/LcAppService.java
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/resources/messages.properties
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/home-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/process-email-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/registration-success.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/result-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/send-email-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/src/main/webapp/WEB-INF/view/user-registration-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/don.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/hero.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/home-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/registration-success.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/result-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/SpringMVCprojectDemo/WEB-INF/view/user-registration-page.jsp
  gyalbusherpa/spring/SpringMVCprojectDemo/target/classes/messages.properties
  gyalbusherpa/spring/SpringMVCprojectDemo/target/maven-archiver/pom.properties
  gyalbusherpa/spring/SpringMVCprojectDemo/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  gyalbusherpa/spring/SpringMVCprojectDemo/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
Labels: good first issue

#55 Gsherpa 35 first crud task
  gyalbusherpa/springBoot/ProductCRUDAssignment/.gitignore
  gyalbusherpa/springBoot/ProductCRUDAssignment/build.gradle
  gyalbusherpa/springBoot/ProductCRUDAssignment/gradlew
  gyalbusherpa/springBoot/ProductCRUDAssignment/gradlew.bat
  gyalbusherpa/springBoot/ProductCRUDAssignment/settings.gradle
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/ProductCrudAssignmentApplication.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/controller/ProductController.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/dto/ErrorDto.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/dto/ProductDto.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/enums/ProductEnum.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/exception/GlobalExceptionHandler.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/exception/ProductAlreadyExistException.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/exception/ResourceNotFoundException.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/model/Product.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/payload/ApiResponse.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/repository/ProductRepository.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/service/ProductService.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/java/com/product/service/ProductServiceImpl.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/resources/application.properties
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/main/resources/productLog.properties
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/test/java/com/product/repository/ProductRepositoryTest.java
  gyalbusherpa/springBoot/ProductCRUDAssignment/src/test/java/com/product/service/ProductServiceImplTest.java
  gyalbusherpa/springBoot/product/.gitignore
  gyalbusherpa/springBoot/product/build.gradle
  gyalbusherpa/springBoot/product/gradlew
  gyalbusherpa/springBoot/product/gradlew.bat
  gyalbusherpa/springBoot/product/settings.gradle
  gyalbusherpa/springBoot/product/src/main/java/com/product/ProductApplication.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/controller/ProductController.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/dto/ErrorDto.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/dto/ProductDto.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/enums/ProductEnum.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/GlobalExceptionHandler.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/ProductAlreadyExistException.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/ResourceNotFoundException.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/model/Product.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/payload/ApiResponse.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/repository/ProductRepository.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/service/ProductService.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/service/ProductServiceImpl.java
  gyalbusherpa/springBoot/product/src/main/resources/application.properties
  gyalbusherpa/springBoot/product/src/main/resources/productLog.properties
  gyalbusherpa/springBoot/product/src/test/java/com/product/ProductApplicationTests.java
Labels: Task

#58 [#35] deleted product project
  gyalbusherpa/springBoot/product/.gitignore
  gyalbusherpa/springBoot/product/build.gradle
  gyalbusherpa/springBoot/product/gradlew
  gyalbusherpa/springBoot/product/gradlew.bat
  gyalbusherpa/springBoot/product/settings.gradle
  gyalbusherpa/springBoot/product/src/main/java/com/product/ProductApplication.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/controller/ProductController.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/dto/ErrorDto.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/dto/ProductDto.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/enums/ProductEnum.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/GlobalExceptionHandler.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/ProductAlreadyExistException.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/exception/ResourceNotFoundException.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/model/Product.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/payload/ApiResponse.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/repository/ProductRepository.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/service/ProductService.java
  gyalbusherpa/springBoot/product/src/main/java/com/product/service/ProductServiceImpl.java
  gyalbusherpa/springBoot/product/src/main/resources/application.properties
  gyalbusherpa/springBoot/product/src/main/resources/productLog.properties
  gyalbusherpa/springBoot/product/src/test/java/com/product/ProductApplicationTests.java
Labels: help wanted

#66 [#35]Adding First CRUD Task
  sumanpaudel/springboot/SpringBootJpaDemo/.gitignore
  sumanpaudel/springboot/SpringBootJpaDemo/build.gradle
  sumanpaudel/springboot/SpringBootJpaDemo/gradlew
  sumanpaudel/springboot/SpringBootJpaDemo/gradlew.bat
  sumanpaudel/springboot/SpringBootJpaDemo/settings.gradle
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/SpringBootJpaDemoApplication.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/controller/EmployeeController.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/controller/LombookLoginController.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/controller/UserController.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/entity/Employee.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/entity/User.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/exception/ResourceNotFoundException.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/repository/EmployeeRepository.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/repository/UserRepository.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/service/EmployeeService.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/service/EmployeeServiceImpl.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/service/UserService.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/java/com/example/springbootjpademo/service/UserServiceImpl.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/main/resources/application.properties
  sumanpaudel/springboot/SpringBootJpaDemo/src/test/java/com/example/springbootjpademo/SpringBootJpaDemoApplicationTests.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/test/java/com/example/springbootjpademo/service/EmployeeServiceImplTest.java
  sumanpaudel/springboot/SpringBootJpaDemo/src/test/java/com/example/springbootjpademo/service/UserServiceImplTest.java
Labels: good first issue
